### ISSUE TITLE
Config.json

### ISSUE THREAD

**Issue by eshimischi** [zllovesuki/slugsurvival#18]
https://github.com/zllovesuki/slugsurvival/blob/5919be91e39051bbb2a0906c2c7aca67c3f25480/config.js#L3

Where or how to get config.json? No idea

**Comment by zllovesuki** [comment]
oops my bad. I will add an example ...

**Comment by eshimischi** [comment]
@zllovesuki still no idea where is ./config/config.json ?

**Comment by zllovesuki** [comment]
@eshimischi I will add one here for example:

```json
{
    "port": 3001,
    "siteURL": "https://slugsurvival.com",
    "dbURL": "https://slugsurvival.objectstore.co/data",
    "trackingURL": "https://tracking.slugsurvival.com",
    "notifyURL": "https://notification.slugsurvival.com",
    "realtimeURL": "https://realtime.slugsurvival.com"
    }
}
```

Preferably you would replace those URLs with your own endpoints.
