### ISSUE TITLE
API return data that is out of date

### ISSUE THREAD

**Issue by ThoseGuysInTown** [zllovesuki/slugsurvival#19]
Was looking at 5j for w2018 ([https://data.slugsurvival.com/term/2178](https://data.slugsurvival.com/term/2178)) and it says that the teacher is McDowell but the official enrollment website (the [my.ucsc.edu](my.ucsc.edu) one) says the teacher will be Adams, the class times are also wrong. 

I was wondering how/how often you update the APIs data?

Thanks

**Comment by zllovesuki** [comment]
Winter 2018 corresponds to term code 2180, but you are looking at 2178, which is Fall 2017. 

CMPS 5J in F2017 is McDowell, and CMPS 5J in W2018 is Adams.
