### ISSUE TITLE
Invalid certificate on data.slugsurvival.com

### ISSUE THREAD

**Issue by natanlao** [zllovesuki/slugsurvival#21]
> data.slugsurvival.com uses an invalid security certificate.
> The certificate is not trusted because it is self-signed.
> The certificate is only valid for ingress.local.
> Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

**Comment by zllovesuki** [comment]
That's interesting, because SlugSurvival doesn't use data.slugsurvival.com as the endpoint anymore.

**Comment by natanlao** [comment]
Ah - I was following some old documentation I think and went to data.slugsurvival.com directly - I didn't encounter this error through slugsurvival.com. Thanks for clarifying!

**Comment by zllovesuki** [comment]
I should probably update outdated documentation as I haven’t done that since the migration to Andromeda.

Please let know the pages that were outdated.

**Comment by zllovesuki** [comment]
Okay, I found sometime to update the documentation a bit: https://slugsurvival.com/explain/opensource
