### ISSUE TITLE
andromeda.miragespace.net firewall?

### ISSUE THREAD

**Issue by tisuela** [zllovesuki/slugsurvival#30]
I've been trying to reach andromeda.miragespace.net from virtual machines hosted by AWS and Google. Testing multiple machines, I cannot open a new connection or ping andromeda.miragespace.net (198.251.90.164) from those machines. 

There are no firewalls on my end that would block off andromeda.miragespace.net. I can access it from my personal computer.

Would appreciate any help on this problem!

**Comment by zllovesuki** [comment]
It seems like one of the servers announcing the Anycast died, and that happens to be in NYC. Try again now.

**Comment by tisuela** [comment]
looks good, ty!
